### ISSUE TITLE
Allow setting different level for airbrake

### ISSUE THREAD

**Issue by milani** [airbrake/airbrake#1073]
Currently, the logger does not allow us setting a different log level for airbrake due to this line:

https://github.com/airbrake/airbrake/blob/ef4c9ceb09c0129d4078c330e4eae9721229c501/lib/airbrake/logger.rb#L57
and this from rails:
https://github.com/rails/rails/blob/fa986ae0cac423bf1ebcb5caeccbecf00c990094/railties/lib/rails/application/bootstrap.rb#L53

Can we disassociate `level` and `airbrake_level`?

**Comment by kyrylo** [comment]
Have you tried setting `airbrake_level` separately?

```
logger = Airbrake::AirbrakeLogger.new(Logger.new(STDOUT))
logger.level = Logger::FATAL
logger.airbrake_level = Logger::ERROR
```

**Comment by milani** [comment]
As you know, rails configurations are usually placed in `config/environments/production.rb` or similar files. Then according to airbrake documents, I set this:

```
    config.log_level         = ENV.fetch('LOG_LEVEL', :warn)
    logger                        = ActiveSupport::Logger.new(STDOUT)
    logger                        = Airbrake::AirbrakeLogger.new(logger)
    logger.airbrake_level = Logger::ERROR
    logger.formatter         = config.log_formatter
    config.logger              = ActiveSupport::TaggedLogging.new(logger)
```

But it does not work because later in the process, rails resets the log level (see the file referenced in the description of the issue):

```
Rails.logger.level = ActiveSupport::Logger.const_get(config.log_level.to_s.upcase)
```

This will set `airbrake_level` automatically back to `warn` in the example above.

The workaround is to use after_initialization hooks:

```
    config.log_level         = ENV.fetch('LOG_LEVEL', :warn)
    logger                        = ActiveSupport::Logger.new(STDOUT)
    logger                        = Airbrake::AirbrakeLogger.new(logger)
    logger.airbrake_level = Logger::ERROR
    logger.formatter         = config.log_formatter
    config.logger              = ActiveSupport::TaggedLogging.new(logger)
    config.after_initialize do
      Rails.logger.airbrake_level = Logger::ERROR
    end
```

But it is not documented and I think it is easily avoidable if airbrake disassociate airbrake_level from logger's level.

**Comment by kyrylo** [comment]
Thanks for the clarifications! 

We do use `after_initialize` in our example. We document how to integrate logger with Rails here:
https://github.com/airbrake/airbrake#configuring-airbrake-logger-integration-with-a-rails-application

I don't feel like changing this behaviour because it was introduced in #903 for very specific reasons:

* by default, we want to maintain the same logger level as the logger that we wrap
* right now `AirbrakeLogger` doesn't need special configuration. With your proposed change everybody will have to set `airbrake_level`, which is not desirable
* with the current design you can still set custom `airbrake_level`, it's still easy

If we disassociate `level`, it's really easy to forget to set `airbrake_level`:

```rb
logger = Logger.new(STDOUT)
ab_logger = Airbrake::AirbrakeLogger.new(logger)
ab_logger.level = Logger::ERROR
ab_logger.warn("oops")
```

Now, this code will not log anything, but it will send an error report to Airbrake. This is unexpected and undesirable IMO.

> But it does not work because later in the process, rails resets the log level (see the file referenced in the description of the issue):

Rails does it so that it can enforce the `config.log_level` option on the Rails logger. It makes sense to me. Our docs recommend to use `after_initialize`. It also makes sense to me :) So far this approach worked well.

**Comment by milani** [comment]
You are right. I close this issue.
