### ISSUE TITLE
when warden is present then try_current_user not work

### ISSUE THREAD

**Issue by skojin** [airbrake/airbrake#1132]
I have app with web login via devise and API with base controller from class ActionController::API, and own authorization via header

So Airbrake::Rack::User.extract https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/user.rb#L14 exit before try_current_user, and errors in API don't have user info

**Comment by kyrylo** [comment]
I am not completely following the issue description but you could:

* delete the `warden` key from Rack env with help of an Airbrake filter (or any other way you prefer)
* add under the `warden` key something responds to the `#user` method and returns a user

**Comment by skojin** [comment]
Issue that project have code that check current_user method, but it not work if another gem is added

**Comment by kyrylo** [comment]
If none of the suggested solutions I pointed out above don't work for your app, you could try to write your own Airbrake filter that retrieves user information and stores it manually. You can access the request object from the notice stash:

https://github.com/airbrake/airbrake#appending-information-from-rack-requests

If you think that the issue is not specific only to your app, I would appreciate it if you could share that filter in the form of a PR. Perhaps, we could merge it.

**Comment by skojin** [comment]
no, thanks
I already make this, my own filter that works only on subset of controllers and uses current_user way

**Comment by kyrylo** [comment]
I'm not sure what else to suggest here. If you need this to be called and you know it'll get you the user info...

https://github.com/airbrake/airbrake/blob/6860375169f120e76cea6df15991d15fe1a30e62/lib/airbrake/rack/user.rb#L23

..then do `rack_env['warden'] = nil` from a filter.
