### ISSUE TITLE
Notifications not sent for Sidekiq errors

### ISSUE THREAD

**Issue by nburt** [airbrake/airbrake#423]
I'm using Airbrake 4.3.1 with Sidekiq 3.4.2 and Rails 4.2.3 and I'm not getting any errors reported within my background jobs. When I use Pry within a Sidekiq worker Sidekiq.error_handlers only returns the standard Sidekiq error logger.

I've listed Airbrake after Sidekiq in my Gemfile. I've also tried adding both `require airbrake/sidekiq` 
and

```ruby
Sidekiq.configure_server do |config|
  config.error_handlers << lambda do |exception, context|
    Airbrake.notify_or_ignore(exception, :parameters => context)
  end
end
```
in an initializer but neither have worked. When I run the above Sidekiq server config code from within the Pry console it does successfully add the Airbrake error handler and send a notification.

Please let me know if there is any other info I can provide.

**Comment by kyrylo** [comment]
Could you please share your Airbrake config?

**Comment by nburt** [comment]
```ruby
Airbrake.configure do |config|
  config.api_key = 'my key'
  config.host    = 'my host'
  config.port    = 80
  config.secure  = config.port == 443
  config.development_environments = ['test']
end
```

**Comment by sauronnikko** [comment]
I'm having the same issue. My airbrake version is ```4.3.1```, my sidekiq ```3.5.0``` and this is my ```airbrake.rb``` initializer:

```ruby
require 'airbrake/sidekiq'

Airbrake.configure do |config|
  config.api_key = ENV['AIRBRAKE_API_KEY']
  config.development_environments = []
end
```

I'm testing this in development, and I'm making sure ```AIRBRAKE_API_KEY``` is set to the proper value.

Thanks for your help.

**Comment by kyrylo** [comment]
Unfortunately, I cannot reproduce this. I can get it working with @sauronnikko's config. I use:

* Sidekiq 3.5.0
* Rails 4.2.4
* Airbrake 4.3.1

@nburt, I noticed that you set `host`, `port` and `secure`. Are you using on-premise Airbrake? I'm not sure why you need this, otherwise.

I've set up a test repo that I used to reproduce this. Please, could you guys try to run it? Make sure to set up your own API key.

I have defined [HardWorker](https://github.com/kyrylo/airbrake-sidekiq-bug-423/blob/master/app/workers/hard_worker.rb) that fails.
Visit `localhost:3000` to trigger it.

**Comment by nburt** [comment]
@kyrylo I found the culprit. We use zeus in development and had written the below helper to start sidekiq:

```ruby
require 'sidekiq/cli'
 
begin
  cli = Sidekiq::CLI.instance
  cli.parse
  cli.run
rescue => e
  raise e if $DEBUG
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
```

Everything works when I start sidekiq with `bundle exec sidekiq` instead.

Thanks for all your help!

**Comment by kyrylo** [comment]
@nburt awesome!

@sauronnikko do you use Zeus as well?
