### ISSUE TITLE
Misleading error message when misconfiguring config.ignore_environments

### ISSUE THREAD

**Issue by sriedel** [airbrake/airbrake#473]
During the migration process I accidentally typed

      config.ignore_environments = %(development test)

instead of %w(...), so a string got assigned instead of an array. Susequently I got an exception that the default notifier was configured. A more pertinent error message, that points to the actual misconfiguration would be great :)

**Comment by kyrylo** [comment]
I do agree it's an irritating typo. That said, one possible solution to this problem would be never using `%w()` for arrays. A more pertinent error message would be handy, but it's extra work (we'd need to validate all the fields). By no means I'm not against this, but at the moment it's not a priority due to the low volume of interest. 

If anyone else stumbles upon this issue, you're welcome to leave a request for this feature.
