### ISSUE TITLE
Why do I have to provide project_id and project_key if my current environment is in ignore_environments

### ISSUE THREAD

**Issue by aguynamedben** [airbrake/airbrake#552]
I just updated to the new airbrake/airbrake-ruby gems. Nice documentation. One question/clarification...

Here's my config/initializers/airbrake.rb:

```ruby
Airbrake.configure do |config|
  config.environment = Rails.env
  config.ignore_environments = %w(development test)

  config.project_id = ENV["AIRBRAKE_PROJECT_ID"]
  config.project_key = ENV["AIRBRAKE_PROJECT_KEY"]
end
```

On CircleCI, with RAILS_ENV="test" and RACK_ENV="test", I get this error that halts my tests from running:

```
Airbrake::Error: both :project_id and :project_key are required
```

Shouldn't the gem not require these values if my environment is ignored? I can always add `unless Rails.env.test?` around my initializer, but that seems to defeat the point of the `.ignore_environments` option you provide.

Not a huge deal, just wondering. Thanks!

–Ben

**Comment by aguynamedben** [comment]
Similarly to the test env, this config also make stuff crash when I try to run a Rake job due to the blank ENV values.

**Comment by kyrylo** [comment]
Hey, @aguynamedben! Thanks for asking. This check happens as early as possible. It's to prevent situations when you think your environment variables are set, but Airbrake doesn't report anything (which means your environment variables are `nil`, so we raise).

> Shouldn't the gem not require these values if my environment is ignored?

This behaviour is unnecessarily complex. We validate the config at the time when you create it and then later we use these values. In order to make sure the same code works for all possible environments, it's easier to make these values mandatory. Currently I am not entirely sure the way it currently works is optimal for users, so in the future this might change.

Pro tip: set these options to dummy values in `circle.yml` to avoid `if Rails.env.test?`.

**Comment by aguynamedben** [comment]
@kyrylo Thanks for the feedback. One more note... I guess it's not clear to me if I should be sending exceptions that happen in test to Airbrake at all, that's why `if Rails.env.test?` is probably a better option for us (for now) than setting the values in `circle.yml`. I guess y'all have to err on the side of failing or else and not risk people silently missing exceptions, so it makes sense to fail extra aggressively if those values are missing.

Thanks again for explaining!

**Comment by kyrylo** [comment]
This will change once https://github.com/airbrake/airbrake-ruby/issues/80 is resolved. I'm planning to rework this part of the library a bit, so it's less confusing.
