### ISSUE TITLE
Improve documentation on add_filter

### ISSUE THREAD

**Issue by JasonBarnabe** [airbrake/airbrake#575]
When migrating to version 5, I'm looking to recreate various filters for exceptions and user agents.

- I find this - https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#configuration, which leads to
- https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#filtering, which leads to
- https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#ignore-by-filter, which includes an example on how to filter on exception class. Great! To figure out how to go on user agent, I follow the link for the Notice public API, which leads to
- https://github.com/airbrake/airbrake-ruby#notice .

This is the piece that seems to be missing a lot of information. It lists out Notice's "modifiable payload". What kind of objects are these? None of them sound like they'd contain the user agent (I would expect "headers" or "request" or something). Are there other pieces of "unmodifiable payload"?

**Comment by kyrylo** [comment]
Hi @JasonBarnabe! Sorry for the confusion.

> To figure out how to go on user agent

We send user agent information by default.

> It lists out Notice's "modifiable payload". What kind of objects are these?

Normally, it's merely [plain Hashes](https://github.com/airbrake/airbrake-ruby/blob/7873fcadf2702179c88bde9bc6ee564136036123/lib/airbrake-ruby/notice.rb#L62).

> None of them sound like they'd contain the user agent (I would expect "headers" or "request" or something)

True. That's because that repo is `airbrake-ruby`. That library is unaware of Rack at all. This repo provides Rack integration. If you want to be able to retrieve arbitrary information from requests, you could use [`Airbrake.add_rack_builder`](https://github.com/airbrake/airbrake#rack). But as I said, we send headers and user agent by default.

With that API you get access to [Rack::Request](http://www.rubydoc.info/gems/rack/Rack/Request), which provides everything you'd want. This API wasn't mentioned in the migration guide doc because it didn't exist back then (it's a 5.1.0 addition; the library is being actively developed).

> Are there other pieces of "unmodifiable payload"?

We don't allow modifying private information such as [notifier information](https://github.com/airbrake/airbrake-ruby/blob/7873fcadf2702179c88bde9bc6ee564136036123/lib/airbrake-ruby/notice.rb#L58).

--

If you have any ideas about how to make our documentation easier to understand please send pull requests. Current migration guide has been improved a lot with community efforts.

**Comment by JasonBarnabe** [comment]
Your answers are good, but people should be able to find this out without having to ask. It boils down to that there doesn't seem to be (or I can't find) documentation on what Notice contains. You say user agent is in there, but this isn't mentioned in the README. If I go to the Wiki, it points me to the migration guide, which ends up pointing me to airbrake-ruby's documentation on it, which would not contain the information I need.

**Comment by kyrylo** [comment]
Thanks Jason, can you suggest any specific information that would help, and point out where you think it might belong?

**Comment by JasonBarnabe** [comment]
The information should include the keys populated by default for use with `:[]` and the associated types of object they will return. Putting it as a page on the wiki would be logical, but the wiki has a banner saying it's outdated, so I dunno.

**Comment by kyrylo** [comment]
So do you think [this section](https://github.com/airbrake/airbrake-ruby#notice--notice) should be updated with a sentence like this one:

> Notice keys conform [Create notice v3](https://airbrake.io/docs/#create-notice-v3) API.

I honestly don't see what else I could suggest to improve docs.

**Comment by kyrylo** [comment]
Let me know if you have some ideas about how to improve the docs. Pull requests are welcome 👍

**Comment by espen** [comment]
I think some basic example would be very helpful. Like how to migrate the following from Airbrake v4:

`config.ignore << "ActionDispatch::ParamsParser::ParseError"`

**Comment by kyrylo** [comment]
If you check [the options table](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#configuration), it mentions what happened to `ignore`, so if you follow the links you will see an example.
