### ISSUE TITLE
How do I ignore ActiveRecord::RecordNotFound?

### ISSUE THREAD

**Issue by varyform** [airbrake/airbrake#598]
* Airbrake version: 5.4.5
* Ruby version: 2.2.2
* Framework name & version: Rails 4.1.15

#### Airbrake config

    notice.ignore! if notice[:errors].any? { |error| error[:type] == 'ActiveRecord::RecordNotFound' }

#### Description

I would like to get working example of ^ which will not turn all 404s into 500s with silently failing "cannot access ignored notice".

**Comment by varyform** [comment]
This can be closed, but probably needs to be documented slightly better.
The issue is that once notice was ignored, you can't access it anymore.

This doesn't work:
```ruby
notice.ignore! if notice[:errors].any? { foo } # matched
notice.ignore! if notice[:errors].any? { bar } # exception
```
This does:
```ruby
notice.ignore! if notice[:errors].any? { foo || bar }
```

**Comment by kyrylo** [comment]
Sorry for the confusion, this is the API you could use to check if a notice is ignored:
https://github.com/airbrake/airbrake-ruby#noticeignored

Normally, it should not silently fail because we raise an [error with a clear message](https://github.com/airbrake/airbrake-ruby/blob/968e54e40c2d8947235b2ce348618470e8bd2483/lib/airbrake-ruby/notice.rb#L165).

I'm glad that you were able to find a workaround, but I suggest you to use `#ignored?`. Happy Airbraking!
