### ISSUE TITLE
Memory spikes after upgrading to v5

### ISSUE THREAD

**Issue by ridiculous** [airbrake/airbrake#610]
* Airbrake version: 5.5.0
* Ruby version: 2.2.4
* Framework name & version: Rails 3.2.22.2

#### Airbrake config

```ruby
# config/initializers/airbrake.rb
require 'airbrake/delayed_job/plugin'
require 'airbrake/resque/failure'

Airbrake.configure do |c|
  c.environment = Rails.env
  c.project_key = ENV['AIRBRAKE_KEY']
  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.ignore_environments = %w(development test)
end

Airbrake.add_filter do |notice|
  notice[:environment].merge!(ENV)
end
```

#### Custom patches

```ruby
# lib/plugin_extensions/airbrake.rb

module Airbrake
  class Rack::Middleware
    # skip notification in case of robot
    def call_with_robot_check(env)
      if App.is_robot(env)
        @app.call(env)
      else
        call_without_robot_check(env)
      end
    end

    alias_method_chain :call, :robot_check
  end

  class << self
    def notify_with_timeout(*args)
      Timeout::timeout(0.3) do
        notify_without_timeout(*args)
      end
    rescue Exception
      # do nothing, failed to reach server in 1 second.
    end

    alias_method_chain :notify, :timeout
  end
end
```

#### Description

After upgrading from v4 to v5, we started experiencing massive spikes in memory usage, sometimes crashing the web server in a matter of minutes. The only change introduced was the upgrade to Airbrake. I wanted to bring this to your attention and see if anyone else has reported a similar issue. NewRelic seemed to point to middleware as a primary contributor to slowness in response time, and always spiked when the memory usage jumped.

Is possible that our monkey patches are wreaking havoc?

**Comment by kyrylo** [comment]
Ugh, sorry about that. I've never heard of this and it was never reported.

I can see you use both DelayedJob and Resque (well, at least according to your `airbrake.rb`). I am not sure this could be a bottleneck (most likely it's not), but I've never tested this scenario. Anyway, I am curious why you do that. Care to elaborate? :)

I do think your monkey-patch may cause some issues. First of all, could you configure your logger and make it use the DEBUG level? This way we could see if there's anything interesting in the logs. Next, I can see you use the Timeout class. It's [known to be dangerous](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/). Since Airbrake v5 is asynchronous by default, increased memory usage might be caused by constant [respawning of its workers](https://github.com/airbrake/airbrake-ruby/blob/95f515244cd63d05308caf05e0357c5c64de9b6d/lib/airbrake-ruby/async_sender.rb#L67-L91), which can die. Airbrake v4 is synchronous by default, so this scenario is not possible. I think it may have similar issues, except that you need more time to see leaking memory (a wild guess, though).

The best way to tell if Airbrake is the bottleneck is to remove your monkey-patch and test. Let me know if that worked.

**Comment by ridiculous** [comment]
Thanks @kyrylo! Good call with the timeout :sweat_smile: and we don't need it anyways, since v4 is async. I'll test it out and let ya know

**Comment by kyrylo** [comment]
Feel free to ping me, when you have time.
