### ISSUE TITLE
Log full HTTP post data

### ISSUE THREAD

**Issue by halida** [airbrake/airbrake#626]
In issue #623 Airbrake can log raw HTTP post data now,
But it limit data size to 512 byte, Airbrake should provide option to support log full post data for better debugging.

- Add config to set HTTP post data size(current 512)
- Add config to set PAYLOAD_MAX_SIZE and MAX_NOTICE_SIZE

**Comment by kyrylo** [comment]
How about using Rack builders?
Check this: https://github.com/airbrake/airbrake#appending-information-from-rack-requests

Simply overwrite `notice[:environment][:body]` with your own code.

**Comment by halida** [comment]
@kyrylo It cannot override PAYLOAD_MAX_SIZE and MAX_NOTICE_SIZE, if post data is more than that, it will be truncated.

**Comment by kyrylo** [comment]
Unfortunately these constants will remain internal. `MAX_NOTICE_SIZE` corresponds to our API, which rejects heavy payload (more than 64KB). It's documented here: https://github.com/airbrake/airbrake-ruby#exception-limit
Right now we don't have any plans to change it.

`PAYLOAD_MAX_SIZE` is not for users, but for our payload truncator (a purely internal class).

As for payload size itself, I think we can only offer reading more bytes. That's what I did in #627. We don't want to expose it because we want to keep our library simple, not bloated like v4 was.

I am not saying this strategy will never change. I feel like what we have now is good for production and I'd like to see how it works (gather more feedback from other users, etc)

Cheers!

**Comment by halida** [comment]
@kyrylo Thanks, I will think about other way.

**Comment by kyrylo** [comment]
@halida I just released a new version of this gem (v5.7.0). You can now set HTTP post data size. This is documented here: https://github.com/airbrake/airbrake#requestbodyfilter

Bear in mind that we stopped sending request bodies by default, so you will have to install that filter either way.

**Comment by halida** [comment]
@kyrylo Thanks, I will use it.
