### ISSUE TITLE
Are the airbrake gems thread safe?

### ISSUE THREAD

**Issue by david-ape** [airbrake/airbrake#629]
Airbrake version: 5.5.0 (airbrake-ruby is 1.5.0)
Ruby version: 2.3.1
Framework: Rails 4.2.6

Are the airbrake and airbrake-ruby gems thread safe. We are thinking about using airbrake in our sidekiq jobs. Thanks!

**Comment by kyrylo** [comment]
I haven't heard of any thread safety issues since the release of v5 (1 year ago). I am not exactly sure what you mean by "using in your Sidekiq jobs" (we provide the Sidekiq integration already), but `Airbrake.notify` *should* be thread-safe because we use Ruby's Queue to deliver errors. In case of `Airbrake.notify_sync` it's your responsibility to make sure it's thread-safe.

It doesn't mean we're free of race conditions. The only thing I can assure you is that I'm yet to see any bug reports :P
