### ISSUE TITLE
Airbrake::Rack::NoticeBuilder#build_notice does not respect exception#to_airbrake method

### ISSUE THREAD

**Issue by stgeneral** [airbrake/airbrake#631]
Building notice with `Airbrake::Rack::NoticeBuilder#build_notice` ignores `exception#to_airbrake` method introduced in `airbrake-ruby` v1.6.0 - https://github.com/airbrake/airbrake-ruby/commit/968e54e40c2d8947235b2ce348618470e8bd2483.

Environment:
- airbrake (5.6.1)
- airbrake-ruby (1.6.0)
- rails (4.1.8)

**Comment by kyrylo** [comment]
It doesn't ignore it because `extract_custom_attributes` doesn't care about who called it. As long as an exception has `#to_airbrake`, it'll be in the dashboard, too. I checked this locally with modified code of `Airbrake::Rack::NoticeBuilder#build_notice` and I can see this feature working.

Please elaborate if you still think it doesn't work for you.
