### ISSUE TITLE
EOFError reported with no useful info

### ISSUE THREAD

**Issue by aviflax** [airbrake/airbrake#637]
Title: `EOFError: end of file reached`

In particular, I need the file and the backtrace.

I don’t know if it matters, but my system uses multithreading  _and_ EventMachine.

![screen shot 2016-12-13 at 10 11 16](https://cloud.githubusercontent.com/assets/141844/21145496/89c76984-c11c-11e6-9e2d-515f7697e43d.png)

### Context

```json
{
  "environment": "production",
  "hostname": "ip-10-251-251-32",
  "language": "jruby/2.3.1",
  "notifier": {
    "name": "airbrake-ruby",
    "url": "https://github.com/airbrake/airbrake-ruby",
    "version": "1.6.0"
  },
  "os": "java",
  "remoteAddr": "54.161.231.99"
}
```

**Comment by kyrylo** [comment]
From my experience, this can be a valid error without a backtrace (we've had a similar case in the past). It is confusing, but absolutely possible. Another possibility is that for some reason we truncate the backtrace completely (likely not the case because we don't wipe out out completely, but drop extra frames).

It's possible to troubleshoot this, though.

1. What's your JRuby version?
2. Could you check your logs at the time when those errors were reported? The backtrace can be truncated
3. Before checking logs, it's better to configure your logger in debug mode and wait for a new occurrence:

    ```rb
    Airbrake.configure do |c| 
      c.logger = Logger.new('airbrake.log').tap { |l| l.level = Logger::DEBUG }
    end
    ```

  You want to look for [this](https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/payload_truncator.rb#L39) message, however any other Airbrake messages will be useful.

**Comment by aviflax** [comment]
> What's your JRuby version?

9.1.6.0

> Could you check your logs at the time when those errors were reported? The backtrace can be truncated

I doubt I’ll be able to get to this any time soon… sorry.
 
> Before checking logs, it's better to configure your logger in debug mode and wait for a new occurrence:

OK, if I see this happening again I’ll make this change and try to capture something.

**Comment by kyrylo** [comment]
Awesome, thanks! I'm going to close this issue because as of now I realistically can't do much here and it can be a valid error.

However I am happy to assist if there's new information.
