### ISSUE TITLE
Include HTTP headers when generating manual notifications?

### ISSUE THREAD

**Issue by a-leung** [airbrake/airbrake#662]
in a rails app, we want to create additional airbrake notifications from a model when certain validations fail and other conditions are met. We want to have HTTP header info with all airbrake notifications, even when notifications are created from the model.

Is there a way to keep the HTTP headers associated with the airbrake notification, even in the model?

**Comment by kyrylo** [comment]
There's no way to do that at the moment. I'm not promising a solution, but I need to think about this.

**Comment by a-leung** [comment]
One way we have considered doing it:

- cache `request` in a class variable from the controller
- when an Airbrake notification is to be sent:
  - then build an Airbrake notification, `notice`
  - then add the `request` into into the `notice.stash[:rack_request] = request`
  - then `Airbrake.notify(notice)`
- result: Airbrake notification with HTTP headers, even from the model

Does this make approach sense? Would there be a better way to do it?

**Comment by kyrylo** [comment]
Everything, but the first item on the list makes sense to me, since this is how you are supposed to use the library (a little tip: there's [`build_notice`][1]). As for the first item, I'm not sure it would be thread-safe. Perhaps, you could use a thread-local variable to workaround this. This might be tricky, but I think if you desperately need this functionality, it can work.

I think in its essence the question is about how to access foreign scopes in Ruby, so
Airbrake can use them. I'm afraid I can't offer anything better at the moment.

[1]: https://github.com/airbrake/airbrake/blob/8b8af2c77ea42b70b949e3b85df6cce3c977ee40/lib/airbrake/rails/action_controller.rb#L32

**Comment by a-leung** [comment]
thanks for the feedback. I just wanted to make sure all options have been explored in considering a solution.
