### ISSUE TITLE
Deprecated Airbrake::Rack::NoticeBuilder issue

### ISSUE THREAD

**Issue by alucardpj** [airbrake/airbrake#668]
In airbrake 5.7.0, I see it removed Airbrake::Rack::NoticeBuilder module, but in some cases, I need to manually build a rack exception notice and send to airbrake before the middleware involved.

e.g. there is an exception raised during rack request execution, I want to catch that exception and send to aibrake, but instead of the original exception, I would like to customize the rack response to a more friendly content without the original backtrace logs etc. 

Previously, airbrake <=5.6.0，I can do it like this:
```
class Twitter::API < Grape::API
  rescue_from :all do |e|
    notice = Airbrake::Rack::NoticeBuilder.new(env["api.endpoint"].env).build_notice(e)
    Airbrake.notify(notice)

    Rack::Response.new({
      success: 5,
      message: I18n.t('api_errors.api.server_error_message')
    }.to_json, 400, { "Content-type" => "application/json" })
  end
end
```
btw, this is in Grape platform "rescue_from" handler environment, [Grape exception handling](https://github.com/ruby-grape/grape#exception-handling)

but now, when Airbrake::Rack::NoticeBuilder was deprecated, how shall I do?

**Comment by kyrylo** [comment]
`Airbrake::Rack::NoticeBuilder` was never a public class, so one should never use it in their own code. Thus `Airbrake::Rack::NoticeBuilder` was never deprecated because it wasn't available to users by design :) We used to expose it via `Airbrake.add_rack_builder`, which is indeed deprecated.

Normally, if you want to integrate with Grape, all you need to do is to add this in your `config.ru` (I recommend this for all users):

```rb
# config.ru
run Airbrake::Rack::Middleware
```

Given that you want some kind of modification, the following should work:


```rb
# config.ru
run Airbrake::Rack::Middleware
```

```rb
# app.rb
class Twitter::API < Grape::API
  rescue_from :all do |ex|
    notice = Airbrake.build_notice(ex)
    notice.stash[:rack_request] = Rack::Request.new(env['api.endpoint'].env)
    Airbrake.notify(notice)
  end
end
```

**Comment by alucardpj** [comment]
Thanks. I've updated my code according to your directions and it works fine!
