### ISSUE TITLE
Set metadata to be sent if an exception occurs?

### ISSUE THREAD

**Issue by phstc** [airbrake/airbrake#696]
Hi

Is there a way to set metadata `context` and `params` like in [`Honeybadger.context`](https://github.com/honeybadger-io/honeybadger-ruby#honeybadgercontext-set-metadata-to-be-sent-if-an-exception-occurs)?

That would be very helpful, because usually the place that `Airbrake.notify(e)` is a high level class, and sometimes the one that raises an exception is super further down, so it would be super cool being able to:

```ruby
def execute
  call_a_all_the_way_down_to_c
rescue e
  Airbrake.notify(e)
end

def c
  # something
rescue e
  Airbrake.context(user_id: user_id)
end
```

**Comment by kyrylo** [comment]
Hi! You can use the [Notice stash](https://github.com/airbrake/airbrake-ruby#noticestash--noticestash). I think it has a similar idea.

```rb
Airbrake.add_filter do |notice|
  if notice.stash[:user_id]
    notice[:params][:user_id] = notice.stash[:user_id]
  end
end


notice = Airbrake.build_notice(e)
notice.stash[:user_id] = user_id
Airbrake.notify(notice) 
```

Alternatively, if you work with custom exceptions, you can set [custom exception attributes](https://github.com/airbrake/airbrake-ruby#custom-exception-attributes).

I know it's not the same, but I can see that your `execute`'s method won't raise because `c` already rescues the exception. Could you perhaps show me another example? I must say I don't fully understand what exactly you want.

**Comment by phstc** [comment]
My need is for something exactly like `Honeybadger.context`, so I can append useful information to the error in any layer, and in the main executor I only `notify`, as the main one does not have access to all meaningful information deep down in all other layers.

```ruby
class A
  def call(...)
    B.new(...).call(...)
  rescue e
    Airbrake.notify(e)
  end
end

class B
  def call(...)
    N.new(...).call(...)
  rescue e
    Airbrake.context(instance_variable_of_b_1: n1, instance_variable_of_b_2: n2, some_other_information: n)
    raise e
  end
end

class N
  def call(...)
  rescue e
    Airbrake.context(instance_variable_of_n_1: n1, instance_variable_of_n_2: n2, some_other_information: n)
    raise e
  end
end
```

Does that make sense?

> Alternatively, if you work with custom exceptions, you can set custom exception attributes.

Most of the exceptions aren't my own, for example `Stripe::Error`.

**Comment by phstc** [comment]
The custom context should be cleaned up every time a `notify` is executed or on a request basis (something like [request_store](https://github.com/steveklabnik/request_store)).

**Comment by kyrylo** [comment]
What about the following API.

You are free to store everything in the Notifier params:

```rb
Airbrake.params[:var_a] = 1
```

When an exception occurs, the notice object takes these values from the notifier and copies over to `params`:

```rb
notice = Airbrake.build_notice('oops')
notice[:params][:var_a] #=> 1
```

You can use that in your filters, if you wish. However you are not required to do that. 

On a `notify/notify_sync` call the params store is cleared:

```rb
Airbrake.notify('oops')
Aribrake.params[:var_a] #=> nil
```

---

I can see an issue with this feature though. What if the `Airbrake.notify` never happens in `A#call`? Then another `Airbrake.notify` call somewhere else will report this data. I understand what you want to achieve, but so far I see fundamental problems with this design.

**Comment by phstc** [comment]
> Airbrake.params[:var_a] = 1

@kyrylo that would work. Is it current available? 

> I can see an issue with this feature though. What if Airbrake.notify never happens in A#call? Then another Airbrake.notify call somewhere else will report this data. I understand what you want to achieve, but so far I see fundamental problems with this design.

`B` and `N` are only setting extra info in `rescue` blocks and they are raising up, but even if `A` does not rescue it and `notify`, worse case would be to have extra params in another exception. Shouldn't be a huge deal, at least for me. It would be a feature to use on your own, you need to know how to use it, otherwise it can lead into unexpected results. 

> The custom context should be cleaned up every time a notify is executed or on a request basis (something like request_store).

That should also be cleared on a notify and request basis.

In a project that I use Honeybadger, this feature helps us a lot. Kinda must have. In the project I'm using Airbrake, it's also must have, I will need to custom code if it can't be like built-in.

**Comment by phstc** [comment]
> Airbrake.params[:var_a] = 1

BTW should it be `context` instead of `params`? It's more like `metadata`, extra info, not necessarily  a param/input/arg.

**Comment by phstc** [comment]
@kyrylo ping?

**Comment by kyrylo** [comment]
Sorry for the delay! I've been distracted by other tasks. Given the growing interest in this feature, I plan to work on it next week. I am going to close this issue in favour of https://github.com/airbrake/airbrake-ruby/issues/187 because that repo is the correct place (airbrake-ruby needs to be modified to implement the feature).

**Comment by hakunin** [comment]
So Airbrake now adds Thread's context to reported errors, thats nice but doesn't solve the context issue.

The workaround with Thread means I have to:

1) dirty Thread.context with airbrake context and then 
2) manually cleanup Thread.context since Rails servers re-use threads and don't clean Thread.context

Rollbar has this implemented nicely instead, others do as well.

**Comment by kyrylo** [comment]
Could you show me an example of Rollbar's API?

**Comment by hakunin** [comment]
https://github.com/rollbar/rollbar-gem#advanced-usage under `Rollbar.scope`

**Comment by phstc** [comment]
![](https://avatars1.githubusercontent.com/u/105652?s=22&v=4) _replaced airbrake with rollbar, `scope` was one of the motivations_

**Comment by kyrylo** [comment]
From my understanding this issue is about:

> @phstc 
>  My need is for something exactly like Honeybadger.context, so I can append useful information to the error in any layer,

I followed your link @hakunin and read the info there. Seems like we're talking specifically about `Rollbar.scope!` here, since it allows attaching info on any layer.

What we offer is this:

```
# Add a new "scope" (rollbar) or "context" (honey badger)
Thread.current[:airbrake] = {}

# Append some data to it
Thread.current[:airbrake].merge!(one: :two)

# Send the attached data
Airbrake.notify(exception)

# Reset the scope
Thread.current[:airbrake] = nil
```

If I understand it correctly, it's exactly the same thing that you guys want.

> @hakunin 
> dirty Thread.context with airbrake context and then

How is setting one custom variable on the current thread mean "dirtying" it?

> manually cleanup Thread.context since Rails servers re-use threads and don't clean Thread.context

That's a fair point, however I don't see why it's a problem. I imagine you can use this API like shown below:

```rb
def send_to_airbrake
  do_stuff
  do_more_stuff
  do_stuff_and_fail
rescue => ex
  Airbrake.notify(ex)
ensure
  Thread.current[:airbrake] = nil
end

def do_stuff
  Thread.current[:airbrake].merge(one: 1)
end

def do_more_stuff
  Thread.current[:airbrake].merge(two: 2)
end

def do_stuff_and_fail
  1/0
end
```

Alternatively, if we agree on the key that everyone is going to use to attach metadata (`:airbrake` in this example), then the library could clean it up for you on every `Airbrake.notify` call, no matter if there's data or not).

> @hakunin 
> So Airbrake now adds Thread's context to reported errors, thats nice but doesn't solve the context issue.

Perhaps, I am missing something?

**Comment by hakunin** [comment]
The `scope(extra: params) { ... }` syntax will clean up the extra params when its done.

Whats missing is the nice high level api that Rollbar provides.

**Comment by kyrylo** [comment]
I don't understand why you need a high level API when you can already use the feature. Do you have any real problems with using what we currently provide?

> The scope(extra: params) { ... } syntax will clean up the extra params when its done.

It's a fair point, that's why I suggested the following:

> @kyrylo
> Alternatively, if we agree on the key that everyone is going to use to attach metadata (:airbrake in this example), then the library could clean it up for you on every `Airbrake.notify` call, no matter if there's data or not).

**Comment by kyrylo** [comment]
Since airbrake-ruby v2.9.0 you can set context with `Airbrake.merge_context`: https://github.com/airbrake/airbrake-ruby#airbrakemerge_context

**Comment by phstc** [comment]
@kyrylo it seems the example is missing the param `(veggies)`:

```ruby
  def load_veggies(veggies)
    Airbrake.merge_context(veggies: veggies)
  end
```
