### ISSUE TITLE
Airbrake requires nokogiri 1.6.8.1 which is vulnerable to CVE-2016-4448 and CVE-2016-4658

### ISSUE THREAD

**Issue by jamilbk** [airbrake/airbrake#701]
Hi there,

We use `bundle-audit` and today our pipeline is failing due to our inclusion of `airbrake` 5.8.1 which depends strictly on `nokogiri` 1.6.8.1. `airbrake` 6.0.0 seems to have the same strict dependency. This version of nokogiri was recently found to be [affected by a couple CVEs](https://github.com/sparklemotion/nokogiri/issues/1615).

I know that nokogiri > 1.7 will break your support for Ruby 2.0.0, but would it be possible to update airbrake's hard nokogiri dependency from `1.6.8.1` to, say `~> 1.7` via a major version bump to allow for these CVEs to be patched?

Thank you,

Jamil

**Comment by kyrylo** [comment]
> We use bundle-audit and today our pipeline is failing due to our inclusion of airbrake 5.8.1 which depends strictly on nokogiri 1.6.8.1.

Howdy!

Nokogiri is our [development dependency](https://github.com/airbrake/airbrake/blob/cde958b02faf0b8b76dc606972dc432f2f96b7a8/airbrake.gemspec#L45). I don't think it really matters whether there are vulnerabilities or not there because we use it only during testing.

If that's possible, I recommend adding airbrake to the ignore list. This gem depends on `airbrake-ruby`, which has no dependencies (except development ones).

**Comment by jamilbk** [comment]
D'oh, that explains it. Glad it's Friday :-). Cheers.

**Comment by kyrylo** [comment]
Happy Airbraking and have fun spending the rest of Friday! 🍺
