### ISSUE TITLE
undefined method `build_notice' for nil:NilClass

### ISSUE THREAD

**Issue by rossmari** [airbrake/airbrake#713]
I caught this error here 
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/middleware.rb#L68
I assume that here we should check if @notifier is present and return if not ?

**Comment by kdeggelman** [comment]
I am seeing this issue as well, but only in environments where we do not configure Airbrake (for us that is development and test).

For context, in our Rails initializer we wrap our Airbrake.configure call in a check to only run in staging and production:
```
if Rails.env.staging? || Rails.env.production?
  Airbrake.configure do |config|
    config.environment = Rails.env
    config.ignore_environments = %w(development test)

    config.project_id = ENV["AIRBRAKE_PROJECT_ID"]
    config.project_key = ENV["AIRBRAKE_PROJECT_KEY"]
  end
end
```
The reason we wrap this call is because we don't have have Airbrake projects for development and testing, see https://github.com/airbrake/airbrake/issues/552

I guess my question is: why is Airbrake trying to `notify_airbrake` in an environment where Airbrake was never configured?

Thanks for the help and let me know if you need any more information.

**Comment by kyrylo** [comment]
@rossmari can I see your config?

@kdeggelman @rossmari what are your airbrake/airbrake-ruby versions?

**Comment by kdeggelman** [comment]
@kyrylo - I fixed this issue by removing the `if Rails.env.staging? || Rails.env.production?` check in our initializer. It looks like the issue from https://github.com/airbrake/airbrake/issues/552 is resolved, and everything works as expected. For the record, we are using airbrake 6.0.0 and airbrake-ruby 2.0.0

**Comment by kyrylo** [comment]
@kdeggelman thanks for the info, that's what I suspected. I'm not closing this because @rossmari might have a different issue.

**Comment by Loremaster** [comment]
I have the same exception `undefined method `build_notice' for nil:NilClass` for such code: 

```
require 'airbrake/sidekiq/error_handler'

if Rails.env.production?
  Airbrake.configure do |config|
    config.project_key = '...'
    config.project_id = ...
    config.environment = ENV["SERVER_NAME"]
    config.ignore_environments = %w(development test)
  end
end
```

If I try to remove `if Rails.env.production?` code then it start to push local error from development to airbrake even though I set `ignore_environments`:

```
require 'airbrake/sidekiq/error_handler'

Airbrake.configure do |config|
  config.project_key = '...'
  config.project_id = ...
  config.environment = ENV["SERVER_NAME"]
  config.ignore_environments = %w(development test)
end
```

How can I fix that?

**Comment by Loremaster** [comment]
I would also add that it continues to report issues to airbrake even if I use `ignore` filter:

```
require 'airbrake/sidekiq/error_handler'

unless Rails.env.production?
  Airbrake.add_filter(&:ignore!)
end

Airbrake.configure do |config|
  config.project_key = '...'
  config.project_id = ...
  config.environment = ENV["SERVER_NAME"]
end
```

**Comment by Loremaster** [comment]
Found my mistake for why `ignore_environments` didn't work! `ENV["SERVER_NAME"]` wasn't set locally for me.

**Comment by repus** [comment]
What

**Comment by kyrylo** [comment]
Normally, you don't need to wrap `Airbrake.configure` with `unless Rails.env.production?` (or similar) checks. This is not something I recommend because `ignore_environments` should "just work".

**Comment by abstrctn** [comment]
I'm running into the same here upgrading from an older version of Airbrake.

Our projects have also historically wrapped `Airbrake.configure` with an environment check. And while I don't feel strongly either way about `ignore_environments` being the preferred fix, it seems to leave us in a tricky spot for developing locally, because if:

1. Airbrake needs to be initialized to not throw the `build_notice` error,
2. Initializing Airbrake requires setting a project_id / project_key,

Then we need to have our `AIRBRAKE_PROJECT_ID` and `AIRBRAKE_PROJECT_KEY` variables set during development, either using environmental variables or some default in the code. Distributing our actual deployed keys to developers seems unnecessary for development purposes (and problematic for larger teams). Is there a recommended setting for these two variables in dev / test environments where the actual project id and key are not available @kyrylo?

**Comment by kdeggelman** [comment]
@abstrctn - I believe it's no longer necessary to provide project id and key for ignored environments. I don't provide a value for `AIRBRAKE_PROJECT_ID` or `AIRBRAKE_PROJECT_KEY`  in development and everything works as expected:
```
Airbrake.configure do |config|
  config.environment = Rails.env
  config.ignore_environments = %w(development test)

  config.project_id = ENV["AIRBRAKE_PROJECT_ID"]
  config.project_key = ENV["AIRBRAKE_PROJECT_KEY"]
end
```

**Comment by abstrctn** [comment]
Ah, you're right - I think the error I was seeing was caused my another bug causing Rails.env to be set incorrectly. Thanks for the quick response @kdeggelman!
