### ISSUE TITLE
Airbrake.notify() broken

### ISSUE THREAD

**Issue by kaluznyo** [airbrake/airbrake#743]
Since Airbrake 6.0.0, use Airbrake.notify into my application, crash, with an error "Stack level Too deep" (log: https://gist.github.com/kaluznyo/f74029142dbbdc2fbfdf41354f8db94e) 

Work fine if I use this method into rails consol, but not in my app

Example of use :
`Airbrake.notify('Checkout error', {error_message: 'Error in checkout#post'})
`

I use Rails 5.1.0 and Ruby 2.4.0

**Comment by kyrylo** [comment]
What are your exact versions of airbrake and airbrake-ruby?

**Comment by kyrylo** [comment]
Do you use HAML, by any chance?

**Comment by kaluznyo** [comment]
I use Airbrake 6.0.0 and airbrake-ruby 2.2.3. No HAML

**Comment by kyrylo** [comment]
Hi @kaluznyo. This is the possible fix: https://github.com/airbrake/airbrake-ruby/pull/222
Could you test?

**Comment by tpope** [comment]
Same issue. https://github.com/airbrake/airbrake-ruby/pull/222 makes it worse, causing the whole server to crash. I poked around with a debugger and the problem is in trying to dump `@payload[:params][:thread][:fiber_variables][:puma_server]` to JSON.

**Comment by kyrylo** [comment]
@tpope I updated https://github.com/airbrake/airbrake-ruby/pull/222
Could you test again?

I could not reproduce this locally. When I call `to_json` on a Puma worker, it gets converted to `{}`.

```
[24] pry(#<Puma::ThreadPool>):2> @workers[0]
=> #<Thread:0x007fb247482c58@puma 001@/Users/kyrylo/.gem/ruby/2.4.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:74 sleep_forever>
[25] pry(#<Puma::ThreadPool>):2> @workers[0].keys
=> [:puma_server]
[26] pry(#<Puma::ThreadPool>):2> @workers[0].to_json
=> "{}"
```

**Comment by tpope** [comment]
No, now it hangs indefinitely. Browser spins rather than getting an error page.

`@payload[:params][:thread][:fiber_variables][:puma_server]` is of class `Puma::Server`, not `Thread`, and contains the entire middleware stack, including (among other things), the application's routes, which are a recursive data structure. `Rails.application.routes.as_json` throws a `SystemStackError`.

Repeated `SystemStackError`s have an increasingly high risk of crashing the server, even if they are caught. And some data structures just hang indefinitely on `as_json` rather than throwing an error, presumably due to tail recursion. (I assume this is what's happening on your latest patch, but I didn't confirm). I really don't see `rescue SystemStackError` as a viable solution.

**Comment by leoamigood** [comment]
I have similar issues, have a stack trace if that helps.

**Comment by mfo** [comment]
Same issue with rails 5.0.3, airbrake 6.0.1 [didnt noticed this trouble with rails 5.0.2 and rails 5.0.2] 
. So maybe an issue linked to an active support update ?

**Comment by kyrylo** [comment]
Thanks everyone for your valuable input! 
I just released [airbrake-ruby v2.2.4](https://github.com/airbrake/airbrake-ruby/blob/master/CHANGELOG.md#v224-may-17-2017) which fixes this bug. 
Sorry for the inconvenience 🍻

**Comment by kyrylo** [comment]
I forgot to mention, just execute `bundle update airbrake-ruby` to upgrade.

**Comment by kaluznyo** [comment]
Thanks. Work fine
