### ISSUE TITLE
Airbrake::Error: the 'default' notifier was already configured

### ISSUE THREAD

**Issue by alvinj01** [airbrake/airbrake#751]
Hi, we are upgrading Airbrake from v4 to the latest v6.
Before we had a shared gem sets the basic configurations, while the application sets app specific configs.

With the latest, this setup gives `Airbrake::Error: the 'default' notifier was already configured`. Is there a way to get around this? Thanks!

**Comment by kyrylo** [comment]
The latest Airbrake gem version (v6.1.1)  doesn't have this problem. Please make sure that you use latest airbrake-ruby (v2.2.5), too.

**Comment by alvinj01** [comment]
thanks!

**Comment by gogosumanth** [comment]
We are getting the same issue with latest versions of airbrake and airbrake-ruby
currently we're at:
airbrake (7.3.3)
      airbrake-ruby (~> 2.10)
    airbrake-ruby (2.10.0)
in both the application and gem.

**Comment by kyrylo** [comment]
Please share your config(s).

**Comment by gogosumanth** [comment]
Thanks Kyrlo for responding.

The main application has this config:
```
Airbrake.configure do |config|
  config.project_id = "some_project_id"
  config.project_key = "some_project_key"
  config.blacklist_keys = Rails.application.config.filter_parameters
end
```
this application has our own gem which also has Airbrake gem as well. Its config is:
```
Airbrake.configure do |config|
  config.project_id = "some_project_id"
  config.project_key = "some_project_key"
end
```

Some threads on internet said this issue was only in some older versions of gem but, i see the issue in the latest version. So, i tried putting conditions ( like `config.project_id = "some_project_id"
 if config.project_id.nil?` ) before setting config in both apps but, it did not work either. Even if it worked by a different way of using conditional statements, i was hoping Airbrake to deal with it without me putting any conditions, as it was doing in 4.x.x versions. 

Really appreciate any guidance here.

**Comment by kyrylo** [comment]
Check if you load the config more than one time. It's likely that you somehow misconfigure it because I haven't heard any similar reports ever since the fix was released.

If it's a Rails app, make sure you config is in `config/initializers/airbrake.rb`. Make sure you don't load that file manually, too.

If it's a Ruby library, make sure you don't configure it in a loop or `require` it more than one time.
