### ISSUE TITLE
Why is Airbrake::Rack::Middleware inserted after ActionDispatch::ShowExceptions in Rails middleware?

### ISSUE THREAD

**Issue by floehopper** [airbrake/airbrake#834]
Currently in a Rails app `Airbrake::Rack::Middleware` is [inserted after][1] `ActionDispatch::DebugExceptions` which comes after `ActionDispatch::ShowExceptions`. The latter uses `ActionDispatch::ExceptionWrapper` to rescue [a set of exception classes][2] by default and respond with the appropriate HTTP status code.

This means that all of the exceptions which are being ignored by Rails are still reported by the Airbrake middleware. So if I want to ignore all these exceptions, which seems like a pretty standard thing to want to do, I have to explicitly add filters for each of them.

I'm probably missing something, but wouldn't it make more sense to insert the Airbrake middleware *before* `ActionDispatch::ShowExceptions` so that the exceptions which are rescued by `ActionDispatch::ShowExceptions` are not seen by Airbrake?

If someone wants Airbrake to report these exceptions (which seems like a bit of an unusual thing to want to do) then they could do this by removing the exception from `ActionDispatch::ExceptionWrapper.rescue_responses`.

If this makes sense to you, then I'd be happy to submit a pull request to make the change.

[1]: https://github.com/airbrake/airbrake/blob/e1e24a7ec25f786858f7090b9627f5a6b8e81ffa/lib/airbrake/rails.rb#L18-L21
[2]: https://github.com/rails/rails/blob/e76e4778d172e2bf43026490256d33a8f5441393/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L9-L22

**Comment by kyrylo** [comment]
As an error monitoring library, we strive to catch all possible exceptions. If we follow the way you suggest, then we will probably lose the ability to track RoutingErrors (and a lot of other errors). Some of our customers are actually interested in those, too. In general, by default, we want to collect more and not less.

That said, I understand why you would like to ignore something you don't find useful. `add_filter` is still the best way to achieve that. I can see that you ignored those exceptions in https://github.com/freerange/site/commit/e7b5717b2d45e7e35a998eec302c20c48ffada9d, and to me it looks like a normal and safe thing to do.

> If someone wants Airbrake to report these exceptions (which seems like a bit of an unusual thing to want to do) then they could do this by removing the exception from ActionDispatch::ExceptionWrapper.rescue_responses.

I don't think it's nice to modify external code, especially in a library that people rely on. For example, if that list suddenly becomes frozen in the next Rails release, it will break all our versions of airbrake that rely on that list (and other people's apps).

I haven't heard any similar complaints, but if more people are interested in what you propose, then we can adopt your filter and include it into the library. We already have some [optional filters](https://github.com/airbrake/airbrake-ruby#optional-filters) that you may want to include in your app, so your filter is a candidate. I am just not sure how many people actually wants this, that's why I don't want to rush with the decision.
