### ISSUE TITLE
Issue with airbrake 9.2.2

### ISSUE THREAD

**Issue by JoeHampton** [airbrake/airbrake#989]
After upgrading an application to airbrake 9.2.2, being logged into the site causes every page to 500 error with the message ```NoMethodError (undefined method `arity' for nil:NilClass):```

I've looked through ```lib/airbrake/rack/user.rb``` in the ```try_to_get``` method, and from what I can tell ```@user.respond_to?(key)``` is returning true, but ```@user.method(key)``` is returning nil. In the project I'm using a library called Flexirest to create user objects, and without looking too deeply into the Flexirest internals, my guess is attributes are meta-programmed in without becoming actual methods.

**Comment by kyrylo** [comment]
Do you have the full backtrace? I suspect this is a bug in Flexirest. It likely uses `method_missing` but doesn't define `respond_to_missing?`.

**Comment by JoeHampton** [comment]
I've been looking through Flexirest and they define ```respond_to_missing?```, but they also undefine ```method```, so that's the reason this is failing. I'm curious why this started happening in airbrake >= 9.2.2 though.

Regardless, this issue can be closed. Thanks for the help!

**Comment by kyrylo** [comment]
Thanks! It's likely because we send performance stats by default now. This call probably triggers the error: https://github.com/airbrake/airbrake/blob/00f9b05c1f02f57dde1ea80030d06ba09290e277/lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb#L38

I think it would be wise to let Flexirest authors know about the issue. Undefining `method` doesn't sound like a good idea because it's a core ruby method.

**Comment by JoeHampton** [comment]
Ah, that makes sense. Thanks for the explanation.

Yeah I'll definitely let the authors know about this issue and ask why that decision was made.
